# Generated by Django 2.1.2 on 2018-10-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='receive_address',
            new_name='receive_user',
        ),
    ]
